name: currency_converter
description: "Easy currency converter app"

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.2.0
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.3
  flutter_hooks: ^0.20.4
  isar: ^3.1.0
  isar_flutter_libs: ^3.1.0
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  isar_generator: ^3.1.0
  build_runner: ^2.4.8
  floor_generator: ^1.4.2
  flutter_gen_runner: ^5.3.1
  flutter_lints: ^3.0.1
  freezed: ^2.3.4
  injectable_generator: ^2.1.6
  json_serializable: ^6.6.2
  retrofit_generator: ^8.0.6

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true